### ISSUE TITLE
This is dead, right ?

### ISSUE THREAD

**Issue by moeenio** [Booligoosh/username.github.io#1]

**Comment by Booligoosh** [comment]
You're talking about Code The Web?

**Comment by moeenio** [comment]
No, this repo

**Comment by Booligoosh** [comment]
Well there's not a lot in it 😆
I originally made it for [this tutorial](https://codetheweb.blog/2018/02/04/github-pages-free-hosting/) and haven't touched it since.

**Comment by moeenio** [comment]
oh ok thanks
